# Configuração de acesso ao banco de dados (ALTERE usuario e senha)
db.url=jdbc:mysql://localhost:3306/catalogo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
db.usuario=root
db.senha=catalogo123
